Show
vikasmishra2104/assignment_db_1 pull request #1
Opened 2020-03-31 19:37 UTC by vikasmishra2104

2020-04-01 06:06 UTC, prernagp requested changes

2020-04-01 06:06 UTC, prernagp commented on database_backend/backendQueries.js
> +app.delete("/maintype/:id", (request, response) => {
api urls should be meaningful names. like when you are computing on employees. so it should be /employee/add,/employee/update

2020-04-01 06:06 UTC, prernagp commented on database_backend/backendQueries.js
> +  console.log("heya");
remove un-necessary logs

2020-04-01 13:27 UTC, vikasmishra2104 commented on database_backend/backendQueries.js
> +  console.log("heya");
done mam,removed all unwanted logs

2020-04-03 06:14 UTC, prernagp approved these changes

2020-04-03 06:14 UTC, merged